### ISSUE TITLE
Bug Report: lambda "is_item_forbidden" function is broken and always returns true

### ISSUE THREAD

**Issue by JustNU** [FuzzyGamesOn/RE2R_AP_World#16]
more info here:
https://github.com/JustNU/RE2R_AP_World/commit/99f23bf4cb0617c3749c8eb065f8941f7b740735

tldr, lambda functions are closure functions and it was always sending last possible location_data (aka it was always sending Victory location), and thus almost always returning true and making forbid_item array on location irrelevant

**Comment by FuzzyGamesOn** [comment]
Awesome, thanks for identifying. Feel free to PR the fix!

**Comment by JustNU** [comment]
I would've PRed it already, but my fork has WAY too many changes (im mostly working on it for fun too, so the quality of code... lacks in some aspects)

**Comment by JustNU** [comment]
disregard above message, i forgot branches exist
https://github.com/FuzzyGamesOn/RE2R_AP_World/pull/18

**Comment by FuzzyGamesOn** [comment]
All good. Thanks for contributing! :grin: Merged.

Good luck with your changes, and feel free to pop into the AP After Dark Discord to talk about any ideas you might have / be messing with for the RE2R rando in our channel: https://discord.gg/Sbhy4ykUKn

**Comment by JustNU** [comment]
You're welcome :) (although the link seems to be dead/don't have permission to join, sadly...)
