### ISSUE TITLE
Bug: Randomized weapons options fail to place all of weapon upgrades sometimes

### ISSUE THREAD

**Issue by JustNU** [FuzzyGamesOn/RE2R_AP_World#26]
creating this for clarity sake, i think this could be related to slightly different way it generates starting weaponry? needs more investigating

**Comment by JustNU** [comment]
after checking with 8 separate generated world, the only guns ever missing any upgrades were starting weapons, so id say that more or less confirmed, gonna look into fixing it

**Comment by JustNU** [comment]
looks like a simple enough fix
https://github.com/FuzzyGamesOn/RE2R_AP_World/pull/27

**Comment by FuzzyGamesOn** [comment]
Just merged. Closing
